openedx/edx-cookiecutters

- CHANGELOG.rst
- cookiecutter-xblock/.travis.yml
- cookiecutter-xblock/README.rst
- cookiecutter-xblock/cookiecutter.json
- cookiecutter-xblock/openedx.yaml
- cookiecutter-xblock/{{cookiecutter.repo_name}}/.dockerignore
- cookiecutter-xblock/{{cookiecutter.repo_name}}/Dockerfile
- cookiecutter-xblock/{{cookiecutter.repo_name}}/Makefile
- cookiecutter-xblock/{{cookiecutter.repo_name}}/README.rst
- cookiecutter-xblock/{{cookiecutter.repo_name}}/manage.py
- cookiecutter-xblock/{{cookiecutter.repo_name}}/requirements.txt
- cookiecutter-xblock/{{cookiecutter.repo_name}}/setup.py
- cookiecutter-xblock/{{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/.tx/config
- cookiecutter-xblock/{{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/__init__.py
- cookiecutter-xblock/{{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/locale/config.yaml
- cookiecutter-xblock/{{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/locale/settings.py
- cookiecutter-xblock/{{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/static/README.txt
- cookiecutter-xblock/{{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/static/css/{{cookiecutter.package_name}}.css
- cookiecutter-xblock/{{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/static/html/{{cookiecutter.package_name}}.html
- cookiecutter-xblock/{{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/static/js/src/{{cookiecutter.package_name}}.js
- cookiecutter-xblock/{{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/{{cookiecutter.package_name}}.py
- docs/decisions/0001-combined-cookiecutter-repo.rst
> adding cookiecutter-xblock

- README.rst
> Fixing format

- .travis.yml
- Makefile
- cookiecutter-django-app/Makefile
- cookiecutter-django-app/README.rst
- cookiecutter-django-app/cookiecutter.json
- cookiecutter-django-app/hooks/post_gen_project.py
- cookiecutter-django-app/tests/conftest.py
- cookiecutter-django-app/tests/test_bake_project.py
- cookiecutter-django-app/{{cookiecutter.repo_name}}/requirements/base.in
- cookiecutter-django-app/{{cookiecutter.repo_name}}/requirements/constraints.txt
- cookiecutter-django-app/{{cookiecutter.repo_name}}/requirements/dev.in
- cookiecutter-django-app/{{cookiecutter.repo_name}}/requirements/test.in
- cookiecutter-django-ida/hooks/post_gen_project.py
- cookiecutter-python-library/hooks/post_gen_project.py
- openedx.yaml
- requirements/base.in
- requirements/base.txt
- requirements/constraints.txt
- requirements/dev.txt
- requirements/test.txt
- requirements/travis.txt
- tox.ini
> Adding testing to repo

- cookiecutter-django-app/{{cookiecutter.repo_name}}/.travis.yml
- cookiecutter-django-ida/{{cookiecutter.repo_name}}/requirements/base.in
- cookiecutter-django-ida/{{cookiecutter.repo_name}}/requirements/constraint.txt
- python-template/{{cookiecutter.placeholder_repo_name}}/.travis.yml
> Changed versions

- README.rst
Fixing Readme instructions based on feedback in #29. Hopefully, with these instruction, its simple to make a new cookiecutter and easier to know how to debug changes to layered cookiecutter.
**JIRA:**
> Modifying README

- CHANGELOG.rst
- README.rst
- docs/decisions/0004-which-cookiecutters-included.rst
Due to no push back on this decision, I am setting this to accepted.
**JIRA:**
> Adding draft ADR

- README.rst
- python-template/{{cookiecutter.placeholder_repo_name}}/docs/decisions/0001-purpose-of-this-repo.rst
> Adding initial ADR to template

- cookiecutter-django-app/{{cookiecutter.repo_name}}/docs/conf.py
- python-template/{{cookiecutter.placeholder_repo_name}}/docs/conf.py
- python-template/{{cookiecutter.placeholder_repo_name}}/docs/index.rst
Renames variables to be more inclusive.
> Make variable names more inclusive

- cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/settings/base.py
- cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/settings/local.py
- cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/settings/utils.py
> Remove local and rsyslog logging (SRE-98)

- .travis.yml
- cookiecutter-django-app/{{cookiecutter.repo_name}}/requirements/constraints.txt
- requirements/base.txt
- requirements/constraints.txt
- requirements/dev.txt
- requirements/test.txt
- requirements/travis.txt
- tests/test_cookiecutter_django_app.py
- tests/test_cookiecutter_django_ida.py
- tests/test_cookiecutter_python_library.py
- tests/test_cookiecutter_xblock.py
- tox.ini
+ modified upgrade test to output more output for errors in the future
> Removing python 3.5 support

- .travis.yml
- cookiecutter-django-app/README.rst
- cookiecutter-django-app/{{cookiecutter.repo_name}}/.travis.yml
- python-template/{{cookiecutter.placeholder_repo_name}}/.travis.yml
- python-template/{{cookiecutter.placeholder_repo_name}}/README.rst
Update links from travis-ci.org to travis-ci.com
> Update links from travis-ci.org to travis-ci.com

- CHANGELOG.rst
- README.rst
- python-template/{{cookiecutter.placeholder_repo_name}}/README.rst
- test_utils/venv.py
Add a brief workflow description for this repository itself and for the repositories it generates.  Also updated virtualenv handling in tests to work more reliably in local development environments.
> Document typical dev workflow

- README.rst
Make the cookiecutter command a little more clear.
> enhance README

- README.rst
- cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/settings/base.py
- cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/settings/local.py
- cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/settings/utils.py
Added logging filters for Remote IP and Used ID to
logging config
SEG-34
> Added logging filters to logging config

- cookiecutter-django-app/{{cookiecutter.repo_name}}/requirements/constraints.txt
- cookiecutter-django-ida/{{cookiecutter.repo_name}}/requirements/constraints.txt
It adds a common constraint pin in cookiecutters
**JIRA:**
[BOM-2257](https://openedx.atlassian.net/browse/BOM-2257)
> Add common constraint

- cookiecutter-django-app/README.rst
- cookiecutter-django-app/cookiecutter.json
- cookiecutter-django-app/{{cookiecutter.repo_name}}/.github/workflows/ci.yml
- cookiecutter-django-app/{{cookiecutter.repo_name}}/Makefile
- cookiecutter-django-app/{{cookiecutter.repo_name}}/requirements/dev.in
- cookiecutter-django-app/{{cookiecutter.repo_name}}/tox.ini
- cookiecutter-django-ida/README.rst
- cookiecutter-xblock/{{cookiecutter.repo_name}}/Makefile
- python-template/cookiecutter.json
- python-template/{{cookiecutter.placeholder_repo_name}}/.github/workflows/ci.yml
- python-template/{{cookiecutter.placeholder_repo_name}}/.github/workflows/pypi-publish.yml
- python-template/{{cookiecutter.placeholder_repo_name}}/Makefile
- python-template/{{cookiecutter.placeholder_repo_name}}/README.rst
- python-template/{{cookiecutter.placeholder_repo_name}}/requirements/ci.in
- python-template/{{cookiecutter.placeholder_repo_name}}/requirements/dev.in
- requirements/ci.in
- tests/test_cookiecutter_django_app.py
- tests/test_cookiecutter_django_ida.py
- tests/test_cookiecutter_python_library.py
**JIRA:**
https://openedx.atlassian.net/browse/BOM-2131
> Updated cookiecutter templates to use GitHub actions for CI

- .github/workflows/ci.yml
The purpose of this PR is to add keywords linter to Django ida in cookiecutters repo.
**JIRA:**
https://openedx.atlassian.net/browse/PSRE-12
> add github action for reserved keywords linter (PSRE-12)

- README.rst
Refactoring readme that I did not find helpful.
> docs: refactoring readme to be helpful to first time visiter

- cookiecutter-django-ida/{{cookiecutter.repo_name}}/requirements/base.in
- cookiecutter-django-ida/{{cookiecutter.repo_name}}/requirements/constraints.txt
chore: removing un-used packages pins.
> chore: removing un-used packages pins.

- .github/workflows/ci.yml
- python-template/{{cookiecutter.placeholder_repo_name}}/.github/workflows/check-reserved-keywords.yml
- python-template/{{cookiecutter.placeholder_repo_name}}/requirements/pip-tools.txt
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/pip-tools.txt
- requirements/pip.txt
- requirements/test.txt
Create separate ci file for check_keywords
**JIRA:**
[PRE-1314](https://openedx.atlassian.net/browse/PSRE-1314)
> chore: add ci file for check_reserved_keywords

- README.rst
- python-template/{{cookiecutter.placeholder_repo_name}}/.github/workflows/upgrade-python-requirements.yml
This PR adds the missing requirements upgrade workflow to the cookie cutters template
**Issue:** #251
> Add req upgrade workflow

- CHANGELOG.rst
- python-template/{{cookiecutter.placeholder_repo_name}}/.github/workflows/upgrade-python-requirements.yml
Grabbed from: https://github.com/openedx/.github/blob/master/workflow-templates/upgrade-python-requirements.yml
> build: update upgrade-python-requirements.yml template

- cookiecutter-django-app/README.rst
- cookiecutter-django-ida/README.rst
We're moving towards a single set of guidelines org-wide.
> docs: Update the contributing guidelines link.

- CHANGELOG.rst
- README.rst
- cookiecutter-django-app/README.rst
- cookiecutter-django-ida/README.rst
- cookiecutter-python-library/README.rst
- python-template/{{cookiecutter.placeholder_repo_name}}/README.rst
> docs: correct the security reporting email addresses

- CHANGELOG.rst
- cookiecutter-django-app/cookiecutter.json
- cookiecutter-django-app/hooks/post_gen_project.py
- cookiecutter-django-ida/cookiecutter.json
- cookiecutter-django-ida/hooks/post_gen_project.py
- cookiecutter-python-library/cookiecutter.json
- cookiecutter-python-library/hooks/post_gen_project.py
- cookiecutter-xblock/cookiecutter.json
- cookiecutter-xblock/hooks/post_gen_project.py
- python-template/cookiecutter.json
- python-template/{{cookiecutter.placeholder_repo_name}}/README.rst
- python-template/{{cookiecutter.placeholder_repo_name}}/docs/conf.py
- python-template/{{cookiecutter.placeholder_repo_name}}/setup.py
- tests/common_tests.py
- tests/conftest.py
- tests/test_cookiecutter_django_app.py
- tests/test_cookiecutter_django_ida.py
- tests/test_cookiecutter_python_library.py
- tests/test_cookiecutter_xblock.py
- tests/venv.py
> feat: ask for the GitHub org that will host the repo

- conftest.py
- python-template/{{cookiecutter.placeholder_repo_name}}/requirements/pip-tools.txt
- python-template/{{cookiecutter.placeholder_repo_name}}/requirements/pip.txt
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/pip-tools.txt
- requirements/pip.txt
- requirements/test.txt
> Upgrade requirements and fix pytest explosion.

- .gitignore
- python-template/{{cookiecutter.placeholder_repo_name}}/.gitignore
> build: ignore venv directories

- cookiecutter-xblock/{{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/{{cookiecutter.package_name}}.py
Ensure a newly-created xblock repo passes quality checks.
> fix: quality fixes on initial xblock creation

- CHANGELOG.rst
- cookiecutter-xblock/{{cookiecutter.repo_name}}/Makefile
Necessary to pas quality tests.
> fix: add selfcheck target to makefile

- cookiecutter-django-app/{{cookiecutter.repo_name}}/Makefile
- cookiecutter-django-ida/{{cookiecutter.repo_name}}/Makefile
- cookiecutter-xblock/{{cookiecutter.repo_name}}/Makefile
issue https://github.com/openedx/edx-cookiecutters/issues/516
Adding compile-requirements
> adding make compile-requirements
