openedx.yaml
python-template/{{cookiecutter.placeholder_repo_name}}/openedx.yaml
python-template/{{cookiecutter.placeholder_repo_name}}/setup.py

This PR:
Marks ths repo as oep-18 compliant and mark repos created with this templates as oep-18 compliants.
Removes python 3.6 and python 3.7 from default classifiers.
CC: @jinder1s

[BD-6] Mark oep-18 in openedx.yaml

---

cookiecutter-django-app/tests/test_bake_project.py
cookiecutter-django-ida/tests/test_ida.py
python-template/{{cookiecutter.placeholder_repo_name}}/README.rst

The generated README currently shows a link to a nonexistent ReadTheDocs site.
This adds a link to the setup and publishing instructions in place of a bad link.

Add doc publishing instructions

---

cookiecutter-django-app/{{cookiecutter.repo_name}}/tox.ini
cookiecutter-django-ida/{{cookiecutter.repo_name}}/pytest.ini
python-template/{{cookiecutter.placeholder_repo_name}}/tox.ini
tox.ini

Don't let pytest find tests in virtualenv packages. This was causing tests to fail locally when running `make test`.
Also, declare `make` external command that tox was complaining about.

Don't let pytest find tests in virtualenv packages

---

README.rst
cookiecutter-django-app/{{cookiecutter.repo_name}}/docs/internationalization.rst
cookiecutter-django-ida/README.rst
cookiecutter-django-ida/{{cookiecutter.repo_name}}/CONTRIBUTING.md
cookiecutter-django-ida/{{cookiecutter.repo_name}}/docs/features.rst
cookiecutter-django-ida/{{cookiecutter.repo_name}}/docs/internationalization.rst
cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/docker_gunicorn_configuration.py
cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/settings/local.py
cookiecutter-python-library/README.rst
cookiecutter-xblock/README.rst
cookiecutter-xblock/openedx.yaml
cookiecutter-xblock/{{cookiecutter.repo_name}}/README.rst
cookiecutter-xblock/{{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/locale/settings.py
python-template/{{cookiecutter.placeholder_repo_name}}/CHANGELOG.rst
python-template/{{cookiecutter.placeholder_repo_name}}/README.rst
python-template/{{cookiecutter.placeholder_repo_name}}/docs/Makefile
python-template/{{cookiecutter.placeholder_repo_name}}/docs/internationalization.rst
python-template/{{cookiecutter.placeholder_repo_name}}/docs/make.bat

We have a lot of insecure HTTP URLs in repos. These all redirect to HTTPS currently, but run the risk of man in the middle attacks before the redirect occurs.
(I left alone any URLs in license files and generated files.)

Use secure URLs

---

Makefile
README.rst
cookiecutter-django-app/hooks/post_gen_project.py
cookiecutter-django-ida/hooks/post_gen_project.py
cookiecutter-python-library/hooks/post_gen_project.py
cookiecutter-xblock/hooks/post_gen_project.py

Simplify local development by adding `Makefile` targets.
Cleanup `ENV` var handling.
@jinder1s Thanks for your explanation on https://github.com/edx/edx-cookiecutters/pull/31 ;
I think I better understand how that works (github vs local).
I understand why we don't default to local (if people invoke it like `cookiecutter https://github.com/edx/edx-cookiecutters -d cookiecutter-xblock`, but it still felt a little "off" to me that running locally, especially after having run `make requirements` , you'd still need to remember to set the `ENV` variable.
So I created a `Makefile` target to invoke `cookiecutter` with all the right arguments, including the setting of `EDX_COOKIECUTTER_ROOTDIR`, by just typing `make cookiecutter-<my-template-name>`.
This leaves the default case in …

Simplify local development and cleanup ENV variable use

---

CHANGELOG.rst
cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/urls.py

Some users of the cookiecutter discovered that we weren't fully configuring CSRF.
[ARCHBOM-1328](https://openedx.atlassian.net/browse/ARCHBOM-1328)

ARCHBOM-1328: Fix CSRF configuration by including csrf.urls patterns

---

Makefile
cookiecutter-django-ida/{{cookiecutter.repo_name}}/manage.py

This way after you bring up your IDA from a cookiecutter, you can
just run  without needing to specify settings every time.

Update the default module path to be a valid path.

---

cookiecutter-django-app/README.rst
cookiecutter-django-ida/README.rst
cookiecutter-python-library/README.rst
cookiecutter-xblock/README.rst

The readmes for the individual cookiecutters were slightly wrong and overly verbose, removed something that did not seem necessary.
**JIRA:**

Fixing documentation in individual cookiecutters

---

CHANGELOG.rst
cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/urls.py

The @edx/edx-aperture team was running into a namespace warning in the Demographics IDA that turned out to be related to these `oauth2_urlpatterns` being imported twice. (You can see [that PR here](https://github.com/edx/demographics/pull/45).)
In the Demographics IDA, we call `oauth2_urlpatterns` as you see suggested here, and it is not included again at (what was previously here) ~ line 34:
```
url(r'^api-auth/', include(oauth2_urlpatterns)),
```
From a quick look, this proposed update to the cookie cutter seems to follow [the pattern suggested in edx/auth-backends](https://github.com/edx/auth-backends#authentication-views).
**JIRA:**
This very loosely comes out of [MICROBA-404](https://openedx.atlassian.net/browse/MICROBA-404).

MICROBA-404 Update oauth2_urlpatterns import in cookie cutter

---

cookiecutter-django-app/{{cookiecutter.repo_name}}/{{cookiecutter.app_name}}/models.py
cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/apps/core/models.py
cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/docker_gunicorn_configuration.py
cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/settings/base.py

This PR intends to remove some deprecated features. (when an app is generated using `cookiecutter-django-ida` template with python 3.8 it installs Django 3 by default and it fails on following features)
1. `SessionAuthenticationMiddleware` was removed in Django 2.0 ([ref](https://docs.djangoproject.com/en/3.0/releases/2.0/#miscellaneous))
2. `python_2_unicode_compatible` decorator is removed in Django 3.0 ([ref](https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis))
**JIRA:**
https://openedx.atlassian.net/browse/BOM-1952

removed deprecated features to make the output compatible with python 3.8

---

CHANGELOG.rst
cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/settings/base.py

`JWT_AUTH_COOKIE` name is required for our JWT Authentication tools, which expect a JWT token to be present in some request cookie.  `JWT_AUTH_COOKIE` specifies the name of the cookie to look for.

Include JWT_AUTH_COOKIE in the base JWT_AUTH settings.

---

CHANGELOG.rst
cookiecutter-django-app/{{cookiecutter.repo_name}}/tox.ini
python-template/{{cookiecutter.placeholder_repo_name}}/tox.ini

Our best practice for docs is to not use
hard line breaks, and to let editors wrap.
See https://open-edx-proposals.readthedocs.io/en/latest/oep-0019-bp-developer-documentation.html#best-practices

remove max-line-length for doc8

---

CHANGELOG.rst
README.rst
cookiecutter-django-ida/README.rst
cookiecutter-python-library/README.rst
python-template/{{cookiecutter.placeholder_repo_name}}/README.rst

- Add some clarification about using a virtualenv for running
cookiecutter.
- Separate the main README into Using and Updating sections.
- Correct the way we talk about Slack, and getting help.
- Minor tweaks to RST formatting.

Updates to READMEs

---

CHANGELOG.rst
cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/apps/core/views.py

Ignore the /healthcheck endpoint by default in monitoring so our
transaction times are closer to what the end user sees.
**JIRA:**
N/A

Ignore healthcheck transaction in IDA cookiecutter

---

CHANGELOG.rst
cookiecutter-django-app/{{cookiecutter.repo_name}}/{{cookiecutter.app_name}}/urls.py

Just make it a suggestion in a comment, otherwise this can cause
trouble if the app is integrated before the `urlpatterns` list
is customized. (In particular, the `r''` default was overriding
all URLs in the IDA.)

ARCHBOM-1570: Don't fill in a sample url pattern for Django apps

---

CHANGELOG.rst
requirements/dev.txt
requirements/test.in
requirements/test.txt
requirements/travis.txt
test_utils/venv.py
tests/test_cookiecutter_django_app.py
tests/test_cookiecutter_django_ida.py
tests/test_cookiecutter_python_library.py
tests/test_cookiecutter_xblock.py

Without this, the pip commands run in the virtualenv of
edx-cookiecutters itself, which causes a very difficult-to-diagnose
flaky test result on Travis CI, possibly involving Travis's pip cache.
Adds `virtualenv` to cookiecutter's dependencies.
Clearing the environment for the subprocess call is essential --
otherwise, the PATH and VIRTUALENV environment variables of the test
runner will leak through to the subprocess.
The virtualenv is created and destroyed again just for the upgrade
command, since it interferes with other tests. For instance, the
pylint and isort checks will try to lint site-packages in the
virtualenv. To fix this we'll want to call a `make quality` command in
the baked project rather than parastically relying on the packages and
configurations in the cookiecutters …

ARCHBOM-1597: Use a virtualenv for `make upgrade` in generated project

---

CHANGELOG.rst
python-template/{{cookiecutter.placeholder_repo_name}}/.readthedocs.yml

Rename it from `doc.{in,txt}` to `docs.{in,txt}`.  This minor change should reduce some
work when setting up Read the Docs(RTD) for a new repo because RTD by default looks for
`requirements/docs.txt`.  By making `requirements/docs.txt` our default file, users don't
need to go fix this after the fact that in their RTD configs.

Rename the docs requirement file.

---

CHANGELOG.rst
Makefile
cookiecutter-django-app/Makefile
cookiecutter-django-app/README.rst
cookiecutter-django-app/{{cookiecutter.repo_name}}/.travis.yml
cookiecutter-django-app/{{cookiecutter.repo_name}}/docs/conf.py
cookiecutter-django-app/{{cookiecutter.repo_name}}/requirements/base.in
cookiecutter-django-app/{{cookiecutter.repo_name}}/tox.ini
cookiecutter-django-ida/Makefile
cookiecutter-django-ida/README.rst
cookiecutter-django-ida/{{cookiecutter.repo_name}}/.travis.yml
cookiecutter-django-ida/{{cookiecutter.repo_name}}/Dockerfile
cookiecutter-django-ida/{{cookiecutter.repo_name}}/requirements/base.in
cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/settings/base.py
cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/urls.py
cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/wsgi.py
cookiecutter-python-library/README.rst
cookiecutter-xblock/{{cookiecutter.repo_name}}/README.rst
cookiecutter-xblock/{{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/locale/settings.py
python-template/{{cookiecutter.placeholder_repo_name}}/.readthedocs.yml
python-template/{{cookiecutter.placeholder_repo_name}}/.travis.yml
python-template/{{cookiecutter.placeholder_repo_name}}/docs/conf.py
python-template/{{cookiecutter.placeholder_repo_name}}/setup.py
python-template/{{cookiecutter.placeholder_repo_name}}/tox.ini

The upgrade to Django 2.2 is long since complete, and the upgrade of
libraries and IDAs to Python 3.8 is wrapping up -- all new repos should
be on 3.8.
**JIRA:**
[ARCHBOM-1598](https://openedx.atlassian.net/browse/ARCHBOM-1598)

ARCHBOM-1598: Drop Python versions below 3.8 and Django below 2.2

---

.github/workflows/ci.yml

and run on PRs created against any branch.
This should allow us to run newly added Github Action on old PRs that are stuck waiting for `required` Github action checks to pass before we can merge those.

Add the ability to trigger Github action manually 

---

python-template/{{cookiecutter.placeholder_repo_name}}/docs/conf.py

This is to make it easier to modify docs if they are wrong or outdated. This has been tested in Devstack's RTD: https://edx.readthedocs.io/projects/open-edx-devstack/en/latest/
Docs for this in: https://github.com/edx/edx-sphinx-theme/pull/97

feat: Adding "edit on github" button to new project's ReadTheDocs

---

CHANGELOG.rst
cookiecutter-django-app/{{cookiecutter.repo_name}}/docs/conf.py

The proper Django Settings were not getting used when building
docs, which caused certain modules to not build in the package
docs.
Fix taken from this PR:
https://github.com/edx/edx-toggles/pull/126
Note: Also adds a changelog entry for [an earlier commit](https://github.com/edx/edx-cookiecutters/commit/cf0bd692744f72914066a414c0554e9c73c793bd).
**JIRA:**
ARCHBOM-1721

ARCHBOM-1721: fix: django package docs

---

CHANGELOG.rst
cookiecutter-django-ida/Makefile
cookiecutter-django-ida/{{cookiecutter.repo_name}}/Dockerfile
cookiecutter-django-ida/{{cookiecutter.repo_name}}/manage.py
cookiecutter-django-ida/{{cookiecutter.repo_name}}/requirements/constraints.txt
cookiecutter-django-ida/{{cookiecutter.repo_name}}/setup.cfg
cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/__init__.py
cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/apps/api/urls.py
cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/apps/core/tests/test_context_processors.py
cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/apps/core/tests/test_views.py
cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/apps/core/views.py
cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/docker_gunicorn_configuration.py
cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/settings/production.py
cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/settings/test.py
cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/urls.py
cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/wsgi.py

Focal! Everywhere! Also dockerfiles that work, let's do that.
Haven't fixed everything downstream of `make test` in that cookiecutter, but getting some things done.
I was originally motivated by the fact that focal newly doesn't require a separate step to make sure that pip3 is the pip being used, since the python3-pip package was recently updated to provide the executable in `/etc/bin`.
**JIRA:**
lol no

Upgrade IDA cookiecutter Dockerfile to use newer Ubuntu

---

cookiecutter-django-app/{{cookiecutter.repo_name}}/.github/workflows/ci.yml
cookiecutter-django-ida/{{cookiecutter.repo_name}}/.github/workflows/docker-publish.yml
docs/decisions/0005-cookiecutter-default-branch.rst
python-template/{{cookiecutter.placeholder_repo_name}}/.github/workflows/ci.yml
python-template/{{cookiecutter.placeholder_repo_name}}/README.rst
python-template/{{cookiecutter.placeholder_repo_name}}/docs/conf.py
python-template/{{cookiecutter.placeholder_repo_name}}/openedx.yaml

After this change, cookiecutter will produce repositories with
assumption the default branch in main

feat: switched default branch to main

---

docs/decisions/0005-store-one-off-scripts.rst
docs/how_tos/running_one_off_scripts.rst
python-template/{{cookiecutter.placeholder_repo_name}}/MANIFEST.in
python-template/{{cookiecutter.placeholder_repo_name}}/setup.py
scripts/update_setup_py.sh

Update cookiecutter setup.py and add migration script for use with cleanup-python-code (or manual run) to update setup.py in existing repositories
**JIRA:**
[ARCHBOM-1772](https://openedx.atlassian.net/browse/ARCHBOM-1772)

feat: update setup.py to advertise constraint and add code migration script

---

python-template/{{cookiecutter.placeholder_repo_name}}/setup.py
scripts/update_setup_py.sh

- move SEMGREP comment inside method so it doesn't get added anew every time the script is run (semgrep can't match comments)
- small refactor of the end of load_requirements to address a weird semgrep issue: https://github.com/returntocorp/semgrep/issues/4221
- clarify what is being printed in the PR message
- add a newline to MANIFEST.in if needed
- only add to MANIFEST.in if it doesn't already have requirements/constraints.txt in it
**JIRA:**
[ARCHBOM-1772](https://openedx.atlassian.net/browse/ARCHBOM-1772)

feat: make update_setup_py.sh idempotent

---

CHANGELOG.rst
cookiecutter-django-ida/{{cookiecutter.repo_name}}/Makefile

This isn't related specifically to any ticket, but when I've used the cookiecutter, I ended up pushing a Docker image to openedx/repo_name because repo_name was not replaced with the actual repo_name on creation (as it is in many other places). This fixes that.
**JIRA:**

fix: interpolate repo_name in django app makefile

---

cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.project_name}}/settings/production.py

fix: Use yaml.safe_load() instead of yaml.load(), which errors in `pyyaml>=6`.
Reference PRs:
https://github.com/openedx/blockstore/pull/146
https://github.com/openedx/blockstore/pull/152

Use yaml.safe_load() instead of yaml.load() in IDA cookiecutter.

---

CHANGELOG.rst
cookiecutter-django-ida/{{cookiecutter.repo_name}}/Dockerfile

Since New Relic is an edX-specific thing, we already inject this code in our internal Dockerfile repo by default.
Remove New Relic injection in Dockerfile code.

fix: remove New Relic from public Dockerfile

---

CHANGELOG.rst
cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.project_name}}/settings/base.py

Use newer name for metrics middleware, and add cookie[1], memory usage,
and deployment middleware. Skip the code owner one that edx-django-utils
offers since most IDAs will be single-owner.
[1] https://2u-internal.atlassian.net/browse/ARCHBOM-2072
"Add CookieMonitoringMiddleware to other IDAs"

feat: Add more monitoring middlewares to IDA

---

cookiecutter-django-app/{{cookiecutter.repo_name}}/{{cookiecutter.app_name}}/urls.py
cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.project_name}}/apps/api/urls.py
cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.project_name}}/urls.py
tests/test_cookiecutter_django_app.py

django has depcreated the use of include and url from
django.conf.urls and instead to use re_path and include from
django.urls
**JIRA:**

feat: replace depreaction use url to re_path also include

---

cookiecutter-django-app/README.rst

repoint the URL so it leads to the desired doc

fix link to IDA instructions

---

cookiecutter-django-app/{{cookiecutter.repo_name}}/docs/conf.py
cookiecutter-django-ida/{{cookiecutter.repo_name}}/Makefile
cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.project_name}}/settings/base.py
python-template/{{cookiecutter.placeholder_repo_name}}/docs/conf.py

This PR squashes the following warnings:
* On DjangoTemplates `context_processors.request`:
?: (admin.W411) 'django.template.context_processors.request' must be enabled in DjangoTemplates (TEMPLATES) in order to use the admin navigation sidebar.
* On `DEFAULT_AUTO_FIELD`:
core.User: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
HINT: Configure the DEFAULT_AUTO_FIELD setting or the CoreConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
* On isort (when running `make validate`):
lib/python3.8/site-packages/isort/main.py:<line>: UserWarning: W0501: The following deprecated CLI flags were used and ignored: -rc!
* On Sphinx `language`:
Invalid configuration …

fix: squash context_processors.request, DEFAULT_AUTO_FIELD, & isort -rc warnings

---

README.rst
cookiecutter-django-ida/README.rst
cookiecutter-python-library/README.rst
python-template/{{cookiecutter.placeholder_repo_name}}/README.rst

Point to the openedx.org shortcut which we can update as needed.

fix: Update the slack invite link.

---

CHANGELOG.rst
cookiecutter-django-app/cookiecutter.json
cookiecutter-django-app/{{cookiecutter.repo_name}}/docs/conf.py
cookiecutter-django-app/{{cookiecutter.repo_name}}/{{cookiecutter.app_name}}/__init__.py
cookiecutter-django-ida/README.rst
cookiecutter-django-ida/cookiecutter.json
cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.project_name}}/settings/base.py
cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.project_name}}/urls.py
cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.project_name}}/wsgi.py
cookiecutter-python-library/cookiecutter.json
cookiecutter-xblock/openedx.yaml
cookiecutter-xblock/{{cookiecutter.repo_name}}/README.rst
cookiecutter-xblock/{{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/locale/settings.py
openedx.yaml
python-template/cookiecutter.json
python-template/{{cookiecutter.placeholder_repo_name}}/README.rst
python-template/{{cookiecutter.placeholder_repo_name}}/openedx.yaml
python-template/{{cookiecutter.placeholder_repo_name}}/setup.py

- Fix or remove `tags` repo metadata in several templates
- Remove extraneous period after short description (required changing the
default/prompt to end with a period so that linter wouldn't complain in
test runs.)
- Move short description to top of readme
- Use project name, not repo name, for package name in setup.py
- Change Django documentation and setup.py references from 2.2 to 3.2

fix: Various (correct variable; tags; placement and punctuation; versions

---

CHANGELOG.rst
cookiecutter-django-app/{{cookiecutter.repo_name}}/Makefile
cookiecutter-django-app/{{cookiecutter.repo_name}}/tests/test_models.py
cookiecutter-django-app/{{cookiecutter.repo_name}}/tox.ini
tests/test_cookiecutter_django_app.py

- Add placeholder test to allow pytest to run without complaining about
not finding any tests (exit code 5).
- Trim tox default envs to just pytest ones; add `doc` env explicitly to
`test-all` Makefile target to compensate.
This just fixes cookiecutter-django-app for now; other cookiecutters can
be fixed once this is shown to work.

fix: Make django-app unit tests work; test this in cookiecutter CI

---

python-template/{{cookiecutter.placeholder_repo_name}}/requirements/pip-tools.txt
requirements/base.txt
requirements/ci.txt
requirements/constraints.txt
requirements/dev.txt
requirements/pip-tools.txt
requirements/pip.txt
requirements/test.txt

`sphinx_rtd_theme` requires docutils<0.18 which causes issues with doc8==1.0.0. This PR pins doc8 to resolve the issue
https://github.com/readthedocs/sphinx_rtd_theme/blob/master/setup.py#L122

Fix requirements upgrade

---

CHANGELOG.rst
python-template/{{cookiecutter.placeholder_repo_name}}/README.rst

Update the README.rst to match guidance in OEP-55

docs: Update template README.rst to match OEP-55 Guidelines

---

CHANGELOG.rst
python-template/{{cookiecutter.placeholder_repo_name}}/README.rst

This will serve as clear indicators:
- Readers will know the content is auto-generated
- Maintainers will know the content needs to be updated
- Maintainers will know where edits are needed
- Linters can find these markers to alert people that work is needed.

docs: add explicit PLACEHOLDER and TODO markers in the readme

---

cookiecutter-xblock/cookiecutter.json

This PR has changes to stop rendering of `workflows/ci.yml` in case of **cookiecutter-xblock** to avoid `'matrix' is undefined error` error.

fix: ignore rendering of workflows/ci.yml to avoid  'matrix' is undefined error

---

python-template/{{cookiecutter.placeholder_repo_name}}/MANIFEST.in
python-template/{{cookiecutter.placeholder_repo_name}}/setup.py

The standard way for setup.py to include Python packages is:
setup(..., packages=find_packages(exclude=[...]), ...)
which will ensure that every package (including sub-packages) in a Python project will be included in the built wheel, unless explicitly excluded.
Up until this point, though, we've been achieving this in a different, very strange way:
setup(..., packages=["<root_package>"], include_package_data=True, ...)
which normally would only include the root packages (for example, `blockstore` but not `blockstore.apps`), except for the fact that we explicitly include Python packages in MANIFEST.in:
recursive-include <root_package> ... *.jpeg *.svg *.py
**Review:**
@regisb can you take a look? and can you fact-check my commit message? Tbh, I don't fully understand the …

build: include packages in a safer, more-standard way

---

python-template/{{cookiecutter.placeholder_repo_name}}/setup.py

This fixes the previous commit,
which accidentally limited `find_packages`
to only finding the root package
instead of the root package and all of its
subpackages.
I found this issue and confirmed the fix
via this PR, which makes a similar change
in Blockstore: https://github.com/openedx/blockstore/pull/202

build: fix setup.py to include sub-packages

---

cookiecutter-django-app/{{cookiecutter.repo_name}}/Makefile
cookiecutter-django-ida/{{cookiecutter.repo_name}}/Makefile

- `transifex` latest version requires `-t` flag with `tx pull` command so updating the templates to include the parameter by default.

fix: fix pull translations command

---

cookiecutter-django-ida/{{cookiecutter.repo_name}}/Makefile
cookiecutter-django-ida/{{cookiecutter.repo_name}}/requirements/test.in

1. The test.in requirements should be constrained by constraints.txt, in addition to base.txt, in case there are common constraints that base would not require but that test.in would (e.g. tox).
2. validation.txt must be compiled before dev.in is compiled into dev.txt, since the latter depends on the former.

fix: a couple of fixes so that `make upgrade` works on a freshly-cut repo

---

python-template/{{cookiecutter.placeholder_repo_name}}/openedx.yaml

Make it clear that the release option won't do anything unless the
repository is in the `openedx` organization in github.
Relates to https://github.com/openedx/build-test-release-wg/issues/203

feat: Update note around release tagging.

---

cookiecutter-django-ida/{{cookiecutter.repo_name}}/CONTRIBUTING.md

We now have a org wide CONTRIBUTING.md that points to our correct
general contributing guidelines.  We don't need repo specific ones that
forward to other contributing docs.

docs: Remove repo specific CONTRIBUTING.md

---

CHANGELOG.rst
cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.project_name}}/urls.py

Get the following errors when running `make html` on a brand new cookiecutter-django-ida template:
.../urls.py:docstring of commerce_coordinator.urls:5: WARNING: Definition list ends without a blank line; unexpected unindent.
.../urls.py:docstring of commerce_coordinator.urls:7: ERROR: Unexpected indentation.
.../urls.py:docstring of commerce_coordinator.urls:9: WARNING: Block quote ends without a blank line; unexpected unindent.
Add linebreaks to squash error.

fix: add extra lines in urls.py docstring to squash sphinx error

---

CHANGELOG.rst
cookiecutter-django-app/{{cookiecutter.repo_name}}/requirements/ci.in
cookiecutter-django-ida/{{cookiecutter.repo_name}}/requirements/ci.in
cookiecutter-xblock/{{cookiecutter.repo_name}}/requirements/ci.in
python-template/{{cookiecutter.placeholder_repo_name}}/requirements/ci.in

The codecov PyPI package is now deprecated. See:
https://community.codecov.com/t/codecov-yanked-from-pypi-all-versions/4259
Its presence in our requirements files are currently causing a lot of CI failures.
It is replaced by codecov-action, a GitHub Action that will upload coverage results to Codecov.
codecov-action is already in edx-cookiecutters in the .github/workflow folder of python-template, on which all other cookiecutters currently depend.

build: remove deprecated codecov CI package in requirements/ci.in

---

CHANGELOG.rst
cookiecutter-django-app/{{cookiecutter.repo_name}}/{{cookiecutter.app_name}}/__init__.py
tests/test_cookiecutter_django_app.py

As of version 3, Django is able to autodetect the AppConfig in apps.py: https://docs.djangoproject.com/en/3.2/ref/applications/
In 4.0+ it relies on this and does not read `default_app_config` at all.

fix: Remove `default_app_config` from app template (dropped in Django 4)

---

CHANGELOG.rst
python-template/{{cookiecutter.placeholder_repo_name}}/CHANGELOG.rst

keepachangelog.com has them because their example is a Markdown file where the version numbers are short-links to a git diff of the changes. Our version numbers are not links.

fix: changelogs shouldn't have square brackets around the version number 

---

cookiecutter-django-app/hooks/post_gen_project.py
cookiecutter-django-ida/hooks/post_gen_project.py
cookiecutter-python-library/hooks/post_gen_project.py
cookiecutter-xblock/hooks/post_gen_project.py

The post_gen hooks have diverged somewhat, which makes it harder to see what can be extracted and deduplicated -- and what is actually supposed to differ between the cookiecutters.
This commit brings the files more closely into alignment:
- Naming of placeholder dir (ADR 3 actually specifies the name) and use of a variable to deduplicate it within the file (xblock, library)
- Line breaks and comments (all)
- Ordering of project/sub_dir in extra_context (app, library)
- Remove `template_` from name of temp dir (ida)
- Remove `python_` from name of placeholder dir variable (app, ida)

refactor: Make post_gen_project hooks as similar as possible

---

CHANGELOG.rst
cookiecutter-django-app/{{cookiecutter.repo_name}}/.coveragerc
cookiecutter-django-ida/{{cookiecutter.repo_name}}/.coveragerc

See https://coverage.readthedocs.io/en/7.2.5/migrating.html & Ned's note in comments of this PR.
----
Via testing, I suspect that:
* Coverage.py file patterns only matches entire directories if the file pattern ends with a slash and asterisk ("/*").
* In addition to the rule above, Coverage.py file patterns that start with a wildcard character only matches entire directories if the file pattern starts with an asterisk and slash ("*/").
Example:
% python
Python 3.8.11 (default, Aug 23 2021, 18:14:59)
>>> import coverage
>>> coverage.version_info
(7, 2, 3, 'final', 0)
>>> from coverage.files import GlobMatcher
>>> GlobMatcher(["*migrations*"], "omit").match("/dir/project/migrations/0001_initial.py")
False
>>> GlobMatcher(["*/migrations/*"], …

fix: correct .coveragerc omitted files globs

---

python-template/{{cookiecutter.placeholder_repo_name}}/README.rst

For new apps and libraries, we'll be publishing their docs under the
single docs.openedx.org domain and not under separate subdomains.
Update the template so that it defaults to that for the docs URL.

docs: Update the place where the docs will be published.

---

requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/test.txt

The constraint mentioned 3.4, and old arrow was producing these warnings:
```
tests/test_cookiecutter_django_app.py::test_bake_selecting_license[AGPL 3.0-GNU AFFERO GENERAL PUBLIC LICENSE]
.../edx-cookiecutters/.tox/py38/lib/python3.8/site-packages/arrow/parser.py:24: DeprecationWarning: invalid escape sequence \[
_ESCAPE_RE = re.compile('\[[^\[\]]*\]')
```

build: no need to pin arrow anymore

---

CHANGELOG.rst
cookiecutter-django-ida/{{cookiecutter.repo_name}}/Dockerfile

mysqlclient 2.2.0 requires Debian package pkg-config to be installed. In some Dockerfiles this also leads to tzdata being installed, which prompts for config and causes the image build to hang, so add `DEBIAN_FRONTEND=noninteractive` to prevent the prompt.
Also organize packages by general purpose. (Would be nice to have comments on all of the groups, but might as well start with this one.)
Fixes https://github.com/openedx/edx-cookiecutters/issues/363

feat: Install pkg-config for IDA Dockerfile

---

cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.project_name}}/settings/base.py

Remove the setting JWT_AUTH_REFRESH_COOKIE
which serves no purpose.
See DEPR: https://github.com/openedx/public-engineering/issues/190

fix: remove unused JWT_AUTH_REFRESH_COOKIE

---

CHANGELOG.rst
cookiecutter-django-ida/{{cookiecutter.repo_name}}/docker-compose.yml

Update the mysql version of the cookie cutter to use mysql 8.0 docker container

chore: Update mysql version from 5.6 to 8.0 for cookie cutter

---

tests/conftest.py
tests/test_cookiecutter_django_app.py
tests/test_cookiecutter_django_ida.py
tests/test_cookiecutter_python_library.py
tests/test_cookiecutter_xblock.py

refactor(test): move baking to a common fixture

---

python-template/{{cookiecutter.placeholder_repo_name}}/setup.py
scripts/update_setup_py.sh

Before this change, the function was dropping extra dependencies. For
example:
If you had a requirements file like the following:
```
Xblock[django]
```
It will output: `Xblock`
The correct output should be `Xblock[django]`
This drops the extras which may have further constraint requirements or
more packages that are required. In the example, the package would need
Django but that dependency would not be visible upstream correctly.

fix: Don't filter out extras for a pip dependency.

---

tests/common_tests.py
tests/conftest.py
tests/test_cookiecutter_django_app.py
tests/test_cookiecutter_python_library.py

I keep finding small improvements, I hope the stream of PRs isn't a nuisance.

test: two small tweaks to the tests

---

CHANGELOG.rst
lib/src/edx_cookiecutter_lib/post_code.py

This prompts users to seek org-specific tweaks when they aren't making repos in the openedx organization.  Axim would prefer not to have private wiki links in public tools, so we don't link to specific instructions like https://2u-internal.atlassian.net/wiki/spaces/ENG/pages/493453499/Repo+deltas+for+edx+GitHub+repos .
I tried to write a test for this, but could not figure out how to capture the stdout from the post hook. 

feat: non-openedx repos get instructions to find tweaks

---

python-template/{{cookiecutter.placeholder_repo_name}}/setup.py
scripts/update_setup_py.sh
scripts/update_setup_py_is_requirement.yaml
scripts/update_setup_py_load_requirements.yaml

See commit messages for details. The big changes are 1) moving the YAML into its own files and 2) ensuring that semgrep is actually installed and used.
Manual testing:
- cd to event-bus-kafka and open a virtualenv
- Run the script from that working directory
- Observe that setup.py has changed
- Observe that `.git/cleanup-python-code-description` exists and that there is no difference in the before/after requires lists it displays

Various improvements to setup.py updater

---

python-template/{{cookiecutter.placeholder_repo_name}}/LICENSE.txt

Per Axim legal, with review from 2U legal, this language was a clarification, not a material difference in the license and can be removed to prevent confusion around edX / 2U code ownership.

chore: Update the AGPL template to remove edX specific language

---

CHANGELOG.rst
python-template/{{cookiecutter.placeholder_repo_name}}/setup.py
scripts/update_setup_py.sh
scripts/update_setup_py_load_requirements.yaml

Update the base template's setup.py to support the full syntax of package extras.
- Support commas and whitespace inside extras declarations, e.g. `some_package[extra_one, extra_two]`
- Raise exception if we spell packages differently in requirement and constraint files, including presence/absence of extras.

feat: Support multiple extras in requirements constraint advertisement

---

CHANGELOG.rst
cookiecutter-django-ida/{{cookiecutter.repo_name}}/Makefile

For IDAs, the configuration repo expects the Makefile target to be called production-requirements. This change makes future IDAs consistent with this.

feat: Change definition of prod_requirements Makefile target

---

cookiecutter-django-app/{{cookiecutter.repo_name}}/Makefile
cookiecutter-django-app/{{cookiecutter.repo_name}}/requirements/base.in
cookiecutter-django-app/{{cookiecutter.repo_name}}/{{cookiecutter.app_name}}/templates/{{cookiecutter.app_name}}/base.html

feat: add atlas support for cookiecutter-django-app
Update cookiecutter-django-app to support atlas for all new apps
This PR prepares the repository to comply with [openedx-translations](https://github.com/openedx/openedx-translations) by doing the following:
**Only for `cookiecutter-django-app`:**
* Use `i18_tool extract` to extract transactions
**How it was tested?**
* Create a django app using the cookiecutter `cookiecutter -o testdir cookiecutter-django-app`
* go to the new app project directory
* Create a virtualenv and upgrade requirements using `make upgrade`
* Install the requirements `make requirements`
* try `make extract_translations`: everything looks fine
* try `make validate`: no errors
References
----------
This pull request is part of the [FC-0012 …

feat: FC-0012 - add atlas support for cookiecutter-django-app

---

cookiecutter-django-ida/{{cookiecutter.repo_name}}/.github/workflows/docker-publish.yml
cookiecutter-django-ida/{{cookiecutter.repo_name}}/Dockerfile
cookiecutter-django-ida/{{cookiecutter.repo_name}}/Makefile

Issue: https://github.com/openedx/edx-cookiecutters/issues/292

feat: Added dev and prod targets.

---

CHANGELOG.rst
python-template/{{cookiecutter.placeholder_repo_name}}/README.rst

See https://github.com/openedx/edx-cookiecutters/issues/396 for details.
Also, promote "Deploying" header, which had previously been under "Getting Started".

feat: Link to getting-started instructions rather than templating them

---

python-template/{{cookiecutter.placeholder_repo_name}}/.readthedocs.yaml

Since this example of the .readthedocs.yaml is in the python-template
cookiecutter, every repo that uses it will have a setup.py and will be
pip-installabale.  So we should have it install it in the docs build
environment by default to make auto documenting the code easier by
default.

fix: Pip install this project in the python environment.

---

CHANGELOG.rst
cookiecutter-xblock/{{cookiecutter.repo_name}}/.github/workflows/ci.yml
cookiecutter-xblock/{{cookiecutter.repo_name}}/tox.ini

Removes pii check from xblock cookiecutter. The check causes any new xblock to automatically start failing ci checks. Since there are only 2 xblocks that have ever needed pii_annotations files (because they talk to the database), it makes more sense just to remove the check. Tested that this check is not run when creating an xblock from this updated cookiecutter.
This duplicates some work from https://github.com/openedx/edx-cookiecutters/pull/412, but extracts it out into its own PR for ease of management and control.

fix: remove pii_check from xblock cookiecutter

---

CHANGELOG.rst
cookiecutter-xblock/{{cookiecutter.repo_name}}/.github/workflows/ci.yml

Removes a step that tries to build using cookiecutter inside an already-created xblock repo. This was failing ci checks.

fix: remove unneeded build step from ci

---

CHANGELOG.rst
cookiecutter-xblock/{{cookiecutter.repo_name}}/requirements/test.in
cookiecutter-xblock/{{cookiecutter.repo_name}}/tests/test_{{cookiecutter.package_name}}.py
cookiecutter-xblock/{{cookiecutter.repo_name}}/tox.ini

Adds a very basic unit test to the cookiecutter-created xblock. This allows coverage to run and gets passed the `No coverage files located` error

fix: add unit test to xblock so there is a coverage file to upload

---

cookiecutter-django-app/{{cookiecutter.repo_name}}/.github/workflows/ci.yml
cookiecutter-xblock/{{cookiecutter.repo_name}}/.github/workflows/ci.yml
python-template/{{cookiecutter.placeholder_repo_name}}/.github/workflows/ci.yml

Update codecov to the latest version and start using the org-wide token for uploads.
See https://github.com/openedx/wg-frontend/issues/179

build: Update codecov and use token

---

CHANGELOG.rst
README.rst
cookiecutter-django-app/README.rst
cookiecutter-django-app/cookiecutter.json
cookiecutter-django-app/{{cookiecutter.repo_name}}/requirements/base.in
cookiecutter-django-app/{{cookiecutter.repo_name}}/tests/test_models.py
cookiecutter-django-app/{{cookiecutter.repo_name}}/{{cookiecutter.app_name}}/models.py
cookiecutter-django-ida/README.rst
cookiecutter-django-ida/cookiecutter.json
cookiecutter-django-ida/hooks/post_gen_project.py
cookiecutter-django-ida/{{cookiecutter.repo_name}}/Dockerfile
cookiecutter-python-library/README.rst
cookiecutter-python-library/cookiecutter.json
cookiecutter-xblock/README.rst
cookiecutter-xblock/cookiecutter.json
cookiecutter-xblock/{{cookiecutter.repo_name}}/Dockerfile
docs/decisions/0003-layered-cookiecutter.rst
docs/decisions/0004-which-cookiecutters-included.rst
lib/README.rst
python-template/cookiecutter.json
python-template/{{cookiecutter.placeholder_repo_name}}/README.rst
python-template/{{cookiecutter.placeholder_repo_name}}/test_utils/__init__.py

This pull request adds "Prompt" messages to all cookie cutters, improving the template creation experience. Additionally, some cleanup was performed.

feat: prompt messages

---

python-template/{{cookiecutter.placeholder_repo_name}}/.github/workflows/pypi-publish.yml

This will fix the warning of "The master branch version has been sunset for gh-action-pypi-publisher"
Close #469

fix: master branch sunset

---

.github/workflows/ci.yml
.github/workflows/upgrade-python-requirements.yml
cookiecutter-django-app/{{cookiecutter.repo_name}}/.github/workflows/ci.yml
cookiecutter-django-ida/{{cookiecutter.repo_name}}/.github/workflows/check-reserved-keywords.yml
cookiecutter-xblock/{{cookiecutter.repo_name}}/.github/workflows/ci.yml
python-template/{{cookiecutter.placeholder_repo_name}}/.github/workflows/ci.yml
python-template/{{cookiecutter.placeholder_repo_name}}/.github/workflows/pypi-publish.yml

This code does not have any dependencies that are specific to any specific
version of ubuntu.  So instead of testing on a specific version and then needing
to do work to keep the versions up-to-date, we switch to the ubuntu-latest
target which should be sufficient for testing purposes.
This work is being done as a part of https://github.com/openedx/platform-roadmap/issues/377
closes https://github.com/openedx/edx-cookiecutters/issues/478

build: Switch to ubuntu-latest for builds

---

.github/workflows/ci.yml
CHANGELOG.rst
cookiecutter-django-app/README.rst
cookiecutter-django-app/{{cookiecutter.repo_name}}/.github/workflows/ci.yml
cookiecutter-django-ida/README.rst
cookiecutter-django-ida/{{cookiecutter.repo_name}}/.github/workflows/check-reserved-keywords.yml
cookiecutter-django-ida/{{cookiecutter.repo_name}}/Dockerfile
cookiecutter-python-library/README.rst
cookiecutter-xblock/{{cookiecutter.repo_name}}/.github/workflows/ci.yml
cookiecutter-xblock/{{cookiecutter.repo_name}}/Makefile
cookiecutter-xblock/{{cookiecutter.repo_name}}/requirements/base.in
cookiecutter-xblock/{{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/{{cookiecutter.package_name}}.py
python-template/{{cookiecutter.placeholder_repo_name}}/.github/workflows/ci.yml
python-template/{{cookiecutter.placeholder_repo_name}}/.github/workflows/pypi-publish.yml
python-template/{{cookiecutter.placeholder_repo_name}}/.readthedocs.yaml
python-template/{{cookiecutter.placeholder_repo_name}}/docs/conf.py
python-template/{{cookiecutter.placeholder_repo_name}}/setup.py

This will update all the actions as follows:
- checkout: v4
- setup-python: v5
- python: 3.12 
Also, Python 3.12 added everywhere.
Close #460 #485

fix: Python 3.8 dropped and support for 3.12 added

---

cookiecutter-django-app/{{cookiecutter.repo_name}}/Makefile
cookiecutter-django-app/{{cookiecutter.repo_name}}/docs/internationalization.rst
cookiecutter-django-ida/{{cookiecutter.repo_name}}/Makefile
cookiecutter-django-ida/{{cookiecutter.repo_name}}/db_keyword_overrides.yml
cookiecutter-django-ida/{{cookiecutter.repo_name}}/docs/internationalization.rst
cookiecutter-xblock/{{cookiecutter.repo_name}}/Makefile
cookiecutter-xblock/{{cookiecutter.repo_name}}/README.rst
python-template/{{cookiecutter.placeholder_repo_name}}/README.rst
python-template/{{cookiecutter.placeholder_repo_name}}/docs/internationalization.rst

This will introduce the following changes:
- typo fixed: transiflex -> transifex
- code-block added
- heading symbol length
- make heading dynamic for xblock cookiecutter
- Old URL with 404 response updated

Fix: Readme

---

CHANGELOG.rst
cookiecutter-python-library/README.rst
cookiecutter-xblock/{{cookiecutter.repo_name}}/requirements/base.in
cookiecutter-xblock/{{cookiecutter.repo_name}}/requirements/dev.in
cookiecutter-xblock/{{cookiecutter.repo_name}}/requirements/pip.in
cookiecutter-xblock/{{cookiecutter.repo_name}}/requirements/test.in
requirements/base.in
requirements/ci.in
requirements/dev.in
requirements/pip-tools.in
requirements/pip.in
requirements/test.in

This just cleans the repo readme and some newlines in `.in` files,
- edx -> Open edX
- trailing whitespace removed.
- new lines in `.in` requirements files.

chore: cleanup

---

cookiecutter-django-app/{{cookiecutter.repo_name}}/Makefile
cookiecutter-django-ida/{{cookiecutter.repo_name}}/Makefile
cookiecutter-xblock/{{cookiecutter.repo_name}}/Makefile

chore: fixed typo

---

python-template/{{cookiecutter.placeholder_repo_name}}/README.rst

This PR fixes the Python CI status badge in the common `README.rst` for all repositories. This was tested with these repositories:
- https://github.com/openedx/openedx-events/pull/485
- https://github.com/openedx/openedx-filters/pull/277

chore: fix python ci status badge

---

cookiecutter-django-app/{{cookiecutter.repo_name}}/manage.py

Pylint fails on freshly created projects if this ignore is here with a:
```
manage.py:21:0: I0021: Useless suppression of 'wrong-import-position' (useless-suppression)
```

style: This ignore is no longer necessary.

---

CHANGELOG.rst
cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.project_name}}/settings/base.py
cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.project_name}}/settings/local.py
cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.project_name}}/settings/production.py
cookiecutter-django-ida/{{cookiecutter.repo_name}}/{{cookiecutter.project_name}}/settings/utils.py

As part of ENT-10092 to correlate logs with DataDog traces, we need the ability to add trace/span IDs to the log lines. However, this being an open source project, we cannot assume a particular format and observability tool. Hence the need to allow operators to completely override the log format.
ENT-10092

feat: [django-ida] allow logging format to be overridden

---

CHANGELOG.rst
cookiecutter-django-app/{{cookiecutter.repo_name}}/.github/workflows/ci.yml
cookiecutter-django-app/{{cookiecutter.repo_name}}/tox.ini
cookiecutter-django-ida/{{cookiecutter.repo_name}}/tox.ini
cookiecutter-xblock/{{cookiecutter.repo_name}}/.github/workflows/ci.yml
cookiecutter-xblock/{{cookiecutter.repo_name}}/tox.ini
cookiecutter-xblock/{{cookiecutter.repo_name}}/translation_settings.py
python-template/{{cookiecutter.placeholder_repo_name}}/setup.py

- Resolved https://github.com/openedx/edx-cookiecutters/issues/524
This PR updates the codebase to be compatible with Django 5.2 while maintaining compatibility with Django 4.2.
Changes Made:
- Update `ci` and `tox` files for cookie-cutter packages
- Ran `django-upgrade` to apply necessary syntax updates for Django 5.2.
- Run tests using `tox` command and resolved the warning 
- Ensured all modifications remain backward-compatible with Django 4.2.
I ran command `git ls-files -z -- '*.py' | xargs -0r django-upgrade --target-version 5.2`

Add Django52 Support
